[package]
name = "extfn"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.101", features = ["full", "extra-traits", "printing"] }
proc-macro2 = "1.0.95"
quote = "1.0.40"
